/*
 * config.h - FWUPD Plugin configuration
 *
 * This is typically generated by meson, but we provide a minimal
 * version for standalone compilation.
 */

#ifndef CONFIG_H
#define CONFIG_H

/* Package name */
#define PACKAGE_NAME "company-i2c-hid"
#define PACKAGE_VERSION "1.0.0"

/* Plugin directory */
#define PLUGIN_DIR "/usr/lib/fwupd/plugins"

/* Quirks directory */
#define QUIRKS_DIR "/usr/share/fwupd/quirks.d"

/* Plugin binary name */
#define PLUGIN_BINARY_NAME "company-i2c-hid"

/* Firmware format magic */
#define FU_COMPANY_I2C_HID_FIRMWARE_MAGIC 0x434F4D50

#endif /* CONFIG_H */
